### PR TITLE
Create LICENSE

### LINKED ISSUE #2: No license file
Please add license file.
In README I can find note about MIT License.
It's very quick and simple. Just add file via Github named LICENSE and choose template MIT LICENSE. Then complete form with your copyright line.

### PR DESCRIPTION
**Pull request by szepeviktor**
Resolves #2

### CODE REVIEW

**Review by EricLBuehler — APPROVED** [review]
MIT is a great license.

**Comment by szepeviktor** [comment]
And already mentioned
https://github.com/bashnick/transformer/blob/d953b08dd6be5e5a5fe19a83b03eb61bb97e4c45/README.md?plain=1#L33

**Comment by szepeviktor** [comment]
@bashnick Friendly ping 🏓

**Review by bashnick — APPROVED** [review]
Make sense, thanks!

**Pull request merged**
